version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725508253.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t phpapp .
      - docker tag phpapp:latest 851725508253.dkr.ecr.ap-south-1.amazonaws.com/phpapp:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 851725508253.dkr.ecr.ap-south-1.amazonaws.com/phpapp:latest
      - echo Deploying the Docker image to EC2...
      - |
        aws ssm send-command \
        --instance-ids "i-0dbf11197b7725257" \
        --document-name "AWS-RunShellScript" \
        --comment "Login to ECR and Deploy Docker Image" \
        --parameters 'commands=[
          "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725508253.dkr.ecr.ap-south-1.amazonaws.com",
          "docker pull 851725508253.dkr.ecr.ap-south-1.amazonaws.com/phpapp:latest",
          "docker stop $(docker ps -q --filter ancestor=851725508253.dkr.ecr.ap-south-1.amazonaws.com/phpapp:latest)",
          "docker run -d -p 80:80 851725508253.dkr.ecr.ap-south-1.amazonaws.com/phpapp:latest"]'

artifacts:
  files:
    - '**/*'

           